"""add visual_ascii column

Revision ID: 21b038260ad7
Revises: 2c05f331bd7b
Create Date: 2026-05-24 11:24:59.965644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b038260ad7'
down_revision = '2c05f331bd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_ascii', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_column('visual_ascii')
    # ### end Alembic commands ###
