"""Fixed Interview model to match service

Revision ID: 677f6b3d6a38
Revises: 0f7c53518601
Create Date: 2026-05-16 11:07:07.008043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677f6b3d6a38'
down_revision = '0f7c53518601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('questions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_answer')
        batch_op.drop_column('question')
        batch_op.drop_column('job_role')
        batch_op.drop_column('ai_feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_role', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('total_score')
        batch_op.drop_column('status')
        batch_op.drop_column('feedback')
        batch_op.drop_column('answers')
        batch_op.drop_column('questions')
        batch_op.drop_column('category')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
