"""Fixed all imports and models

Revision ID: b77c9ad791a5
Revises: 9bf6b8b60abe
Create Date: 2026-05-16 16:00:40.342072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b77c9ad791a5'
down_revision = '9bf6b8b60abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmaps')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('job_type',
               existing_type=postgresql.ENUM('full-time', 'part-time', 'internship', 'remote', name='job_types'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('full-time', 'part-time', 'internship', 'remote', name='job_types'),
               existing_nullable=True)

    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('current_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roadmaps_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='roadmaps_pkey')
    )
    # ### end Alembic commands ###
